# Generated by Django 4.0.6 on 2022-07-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
    ]
