# Generated by Django 4.0.6 on 2022-07-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_description_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deadline_date',
            field=models.DateTimeField(),
        ),
    ]
