# Generated by Django 4.0.6 on 2022-07-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220721_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lifecode',
            field=models.TextField(default=''),
        ),
    ]
